# Generated by Django 4.1.2 on 2022-10-11 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchApiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videodatabase',
            old_name='thumbnailsUrls',
            new_name='thumbnail_url',
        ),
    ]
